# Copyright 2024 Secure Sauce LLC
# SPDX-License-Identifier: BUSL-1.1
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .
